INFO:websocket_server.websocket_server:Listening on port 80 for clients..
INFO:websocket_server.websocket_server:Server terminated.
INFO:websocket_server.websocket_server:Listening on port 80 for clients..
INFO:websocket_server.websocket_server:Server terminated.
INFO:websocket_server.websocket_server:Listening on port 80 for clients..
WARNING:websocket_server.websocket_server:Client must always be masked.
WARNING:websocket_server.websocket_server:Client must always be masked.
----------------------------------------
Exception happened during processing of request from ('45.95.147.3', 49330)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.95.147.3', 49342)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.221.219.14', 51586)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
WARNING:websocket_server.websocket_server:Client must always be masked.
----------------------------------------
Exception happened during processing of request from ('185.167.46.219', 50586)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('1.145.200.119', 1068)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('216.218.206.68', 38914)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('71.6.232.4', 51966)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.112.111.114', 55278)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('107.189.14.98', 38728)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('138.68.161.204', 56758)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('124.103.77.167', 50321)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
WARNING:websocket_server.websocket_server:Client must always be masked.
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
----------------------------------------
Exception happened during processing of request from ('69.70.59.38', 51435)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
WARNING:websocket_server.websocket_server:Client must always be masked.
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 57870)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 57858)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 55584)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 54002)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 32830)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 57132)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 57334)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 45988)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 54116)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 51402)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 49916)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.146.164.110', 55806)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('209.97.141.112', 41406)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('209.141.48.211', 33524)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('94.180.25.214', 61880)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('209.17.97.98', 61611)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('199.195.251.213', 50032)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('209.141.58.209', 58018)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('212.103.114.237', 45116)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('190.103.39.25', 44413)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('193.118.53.202', 47142)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('203.159.80.44', 59244)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('111.241.119.160', 52503)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('45.181.18.11', 47951)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('176.214.40.7', 42987)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('107.189.31.252', 47120)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('107.189.14.98', 51098)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('37.49.230.221', 54110)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('37.49.230.221', 55576)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('112.30.110.31', 34559)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 301, in handshake
    headers = self.read_http_headers()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 290, in read_http_headers
    assert http_get.upper().startswith('GET')
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.119.64.253', 51333)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('37.49.230.221', 61026)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('37.49.230.221', 61092)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('91.224.185.226', 46540)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('181.192.2.102', 44381)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.73.154.141', 51318)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 176, in handle
    self.handshake()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 304, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 165, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.6/socketserver.py", line 726, in __init__
    self.finish()
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 338, in finish
    self.server._client_left_(self)
  File "/home/narita/.local/lib/python3.6/site-packages/websocket_server/websocket_server.py", line 144, in _client_left_
    self.client_left(client, self)
  File "main.py", line 63, in client_left
    print("client({}) disconnected".format(client['id']))
TypeError: 'NoneType' object is not subscriptable
----------------------------------------
INFO:websocket_server.websocket_server:Client closed connection.
INFO:websocket_server.websocket_server:Client closed connection.
WARNING:websocket_server.websocket_server:Client must always be masked.
